### ISSUE TITLE
When using a before notification Remote_file in install freaks out

### ISSUE THREAD

**Issue by axelrtgs** [criteo-cookbooks/nssm#33]
because the zip file hasn't been extracted yet while checking to run the before notification the resource freaks out and crashes the chef run.

Need to add a test to catch this and also apply the fix which is adding the following line to the remote_file resource:

`only_if {::File.exist?("#{Chef::Config[:file_cache_path]}/#{basename}/#{system}/nssm.exe")}`

will make the change as soon as i'm done some more local testing.

**Comment by Annih** [comment]
Could describe the error and the setup that triggers it?
i.e. please provide a sample recipe to reproduce + the error message :)

**Comment by axelrtgs** [comment]
just add a before notification to an NSSM resource and you will trigger the error. this is a remaining bug that was not fixed or merged when the PR to fix the zip functionality was merged. I just finally got around to fixing it since no one else had a chance.

**Comment by Annih** [comment]
I'm sorry @axelrtgs I'm not having difficulties to reproduce with a simple before notification/subscription.
Here is the code I used:
```ruby
log 'before notification' do
  notifies :install, 'nssm_install[Install NSSM]', :before
end
log 'before subscription' do
  action :nothing
  subscribes :write, 'nssm_install[Install NSSM]', :before
end
include_recipe 'nssm'
```
I used Chef `12.18.31`, the only bug I encountered was with the `rubyzip` gem, but your fix didn't help. I'm sure you have a different setup. Could you share it with me?

**Comment by axelrtgs** [comment]
I am not at my computer right now but it’s the other way around. Syntax may be a bit off but it’s something like this:

Execute ‘do something’ do
Command ‘kill all the things’
Action :nothing
End

Nssm ‘service’ do
 Nssm service options
Notify :run execute[do something] :before
End

Also make sure you’re cache is clean and there’s no nssm stuff in there. 

What happens is because the zip hasn’t been downloaded or extracted yet when it tries to evaluate if it should copy the file because it doesn’t exist it panics. You can use anything that get notified before. Doesn’t have to be execute. 

Also for the ruby zip thing I had the same error I solved it by having my cookbook that uses nssm explicitly install the ruby zip gem before using nssm. I wasn’t sure that should be part of nssm or not but I’m sure we can find a way to fix it. 

Sorry for the miscommunications seems like we both were having some trouble understanding each other.

**Comment by axelrtgs** [comment]
Just wanted to follow up on this to see if you need more information in case i wasn't clear on some aspect.
Thanks for your time,
