### ISSUE TITLE
Java Heap error

### ISSUE THREAD

**Issue by AngariDinesh** [criteo-cookbooks/nssm#40]
Hi I am creating 100 nssm service services to run my application.

After running some time i am getting nssm stopped working.

Please help me how can i handle this.

**Comment by Annih** [comment]
Hello @AngariDinesh 

I'm not sure to understand why do you think your bug might be related to this Chef cookbook.
It seems to be more an NSSM related bugs, don't you think?

I suggest you to have a look at the Windows event logs to understand a bit more the context of your bug, then report it to the nssm maintainer. (cf https://nssm.cc/bugs)
